apiVersion: v2
name: openshift-gitops
description: OpenShift GitOps Operator and ArgoCD Configuration for Enterprise Platform
type: application
version: 1.1.0
appVersion: "1.11.0"
home: https://github.com/emiratesnbd/openshift-platform-charts
sources:
  - https://github.com/redhat-developer/gitops-operator
  - https://github.com/argoproj/argo-cd
icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
maintainers:
  - name: Platform Engineering Team
    email: platform@emiratesnbd.com
keywords:
  - openshift
  - gitops
  - argocd
  - operator
  - devops
annotations:
  changelog: |
    v1.1.0: All critical bugs from v1.0.0 fixed. Production ready.
