{{- if .Values.operator.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "openshift-gitops.operatorNamespace" . }}
  labels:
    {{- include "openshift-gitops.labels" . | nindent 4 }}
    openshift.io/cluster-monitoring: "true"
  {{- with (include "openshift-gitops.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}

{{- if .Values.argocd.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "openshift-gitops.argocdNamespace" . }}
  labels:
    {{- include "openshift-gitops.labels" . | nindent 4 }}
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/managed-by: {{ include "openshift-gitops.argocdNamespace" . }}
  {{- with (include "openshift-gitops.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
